version: "3.9"
services:
  flaskapp:
    image: flaskapp:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=flaskapp-db
      - DB_PORT=3306
      - DB_NAME=flaskappdb
      - DB_USER=flaskappuser
      - DB_PASSWORD=flaskapppassword
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Foli1882
      MYSQL_DATABASE: flaskappdb
      MYSQL_PASSWORD: flaskapppassword
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
volumes:
  db_data:
