# version: '3'
# services:
#   flaskapp:
#     image: flaskapp:latest
#     ports:
#       - 5000:5000
#     depends_on:
#       - db
#     environment:
#       - FLASK_APP=app.py
#       - MYSQL_HOST=db
#     networks:
#       - mynetwork

#   db:
#     image: mysql:8.0
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: Foli1882
#       MYSQL_DATABASE: flaskapp
#     volumes:
#       - db_data:/var/lib/mysql
#     networks:
#       - mynetwork

# volumes:
#   db_data:

# networks:
#   mynetwork:

version: "3"
services:
  app:
    build: .
    links:
      - db
    restart: on-failure:3
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro


